# Generated by Django 5.2.11 on 2026-02-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('ENT', 'ENT Specialist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('Endocrinologist', 'Endocrinologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Pulmonologist', 'Pulmonologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Rheumatologist', 'Rheumatologist'), ('Nephrologist', 'Nephrologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('General Surgeon', 'General Surgeon'), ('ENT Surgeon', 'ENT Surgeon'), ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Vascular Surgeon', 'Vascular Surgeon')], default='General Physician', help_text='Select specialization. The Department will automatically update to match this.', max_length=100),
        ),
    ]
