# Generated by Django 5.2.11 on 2026-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_medicalreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
