# Generated by Django 5.2.11 on 2026-02-06 16:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_medicalreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='reports/'),
        ),
    ]
